# Generated by Django 5.2.5 on 2025-08-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos_app", "0003_video_thumbnail_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="category",
            field=models.CharField(
                help_text="Category or genre of the video.",
                max_length=50,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the video entry was created.",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional detailed description of the video.",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail_url",
            field=models.ImageField(
                blank=True,
                help_text="Optional thumbnail image stored in the 'thumbnails/' directory.",
                null=True,
                upload_to="thumbnails/",
                verbose_name="Thumbnail",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(
                help_text="Title of the video.", max_length=200, verbose_name="Title"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video_file",
            field=models.FileField(
                blank=True,
                help_text="Uploaded video file stored in the 'videos/' directory.",
                null=True,
                upload_to="videos/",
                verbose_name="Video File",
            ),
        ),
    ]
